### ISSUE TITLE
Prepare Backlog for Sprint 02

### ISSUE THREAD

**Issue by Fle-bihh** [SEAME-pt/SEAME-WarmUp-HotWheels#68]
Duration of Sprint 02 : Monday 18/11 --> Friday 29/11
 Research the work that needs to be done and organize into issues.

**Comment by reomelo** [comment]
The main tasks for Sprint 02 have been created and are available in the respective view on the team's Project.
This tasks can be updated later, they're just an overall assessment of what needs to be done
